name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build the Docker image
        run: docker build -t us-central1-docker.pkg.dev/nomadic-grid-382206/go-echo-boilerplate/images:latest .

      - name: Push the Docker image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/nomadic-grid-382206/go-echo-boilerplate/images:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses
