apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-echo-boilerplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-echo-boilerplate
  template:
    metadata:
      labels:
        app: go-echo-boilerplate
    spec:
      containers:
      - name: go-echo-boilerplate
        image: us-central1-docker.pkg.dev/nomadic-grid-382206/go-echo-boilerplate/images:tag1
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
